version: '3.8'

services:
  nginx:
    build: ./nginx
    image: shane-status-page-nginx:latest
    env_file: settings.env
    deploy:
      replicas: 1
    volumes:
      - data_dir:/data
    secrets:
      - source: cssnr.com.crt
        target: /etc/ssl/cssnr.com.crt
      - source: cssnr.com.key
        target: /etc/ssl/cssnr.com.key
      - source: blueteam_basic_http_auth
        target: /etc/nginx/auth.users
    ports:
      - "443:443"

secrets:
  cssnr.com.crt:
    file: /etc/ssl/cssnr.com.crt
  cssnr.com.key:
    file: /etc/ssl/cssnr.com.key
  blueteam_basic_http_auth:
    file: ~/basic_http_auth

volumes:
  data_dir:
  redis_data:
  flower_data:
